### PR TITLE
added netteForms JS integrity checksum

### PR DESCRIPTION
**Pull request by vjirovsky**
This pull request is about adding Javascript's integrity checksum (SRI) into template of Nette project - because netteForms is loaded from CDN (nette.github.io).

There is more informations about SRI:
https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity

### CODE REVIEW

**Comment by vjirovsky** [comment]
ping

**Comment by dg** [comment]
The file is updated continuously so there can't be integrity check.

**Comment by vjirovsky** [comment]
I think there should be some versioning management of this file, when it's referenced to external CDN. 

There should be two access to file (generated by Nette CI release task):
1. latest 
- reference to https://nette.github.io/resources/js/3/netteForms-latest.js - with no integrity check, as symlink to last version (netteForms-3.0.3.js)

2. specific version
- reference to https://nette.github.io/resources/js/3/netteForms-3.0.1.js , netteForms-3.0.2.js, netteForms-3.0.3.js - with recommended integrity check

For me it's similar like Docker image version tags - you don't want to use "latest" in production, but specific version, and after testing of new version, you want to upgrade.

So CI task would generate:
1. latest file
2. specific version file
3. integrity checksum for specific JS file version into template

**Comment by dg** [comment]
Which means a really lot of work. Which I do not want to do :-)

Preferred way is to not use GitHub CDN. It exists mainly for examples in repository and Sandbox.

**Pull request closed without merging**
