### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by basicshapes**
changed Tilde Operator to Caret Operator in require

### CODE REVIEW

**Comment by Majkl578** [comment]
:-1: Nette doesn't follow semver so 2.4 could easily break code when it comes out.

**Comment by basicshapes** [comment]
OK, got it. Not quit sure, but would the wildcat then do the job? ( "2.*")

**Comment by dg** [comment]
@pixelsailer What is your intention?

**Comment by basicshapes** [comment]
My intention is to get rid of the following warning:

```
Warning: The lock file is not up to date with the latest changes in composer.json.
You may be getting outdated dependencies.
Run update to update them.
Nothing to install or update
Generating autoload files
```

After `$ composer create-project nette/web-project project` you have to `cd` into web-project and run `$ composer update` Thats no big deal at all, but whit my pull you get rid of this and in both cases you have to update the composer.json on releases of new versions (like Majkl578 maintained).

**Comment by JanTvrdik** [comment]
I don't understand how the cared operator may fix the warning.

**Comment by hrach** [comment]
IMO it will be mistake in line endings. .gitattributes should force LF to composer.json.

**Comment by JanTvrdik** [comment]
Verified, the [hash in composer.lock](https://github.com/nette/web-project/blob/v1.0/composer.lock#L7) is MD5 of [composer.json](https://github.com/nette/web-project/blob/v1.0/composer.json) with CRLF line endings.

**Comment by dg** [comment]
Wouldn't it be better to send PR to the Composer instead of fixing it in .gitattributes?

**Comment by JanTvrdik** [comment]
@dg Yes, that is also a possibility. Hint for anyone with a bit of time https://github.com/composer/composer/blob/2e73811211b7ea6de8de578fa50746fe679f2297/src/Composer/Factory.php#L309

**Comment by basicshapes** [comment]
Ok, i think i got it now. I thought nette follows semversions, but as Majkl578 said, nette issn't and this pull will be closed.

**Comment by hrach** [comment]
https://github.com/composer/composer/issues/3044

**Pull request closed without merging**
