### PR TITLE
.htaccess: allow /. in url if real file not exists

### PR DESCRIPTION
**Pull request by adaamz**
Consider virtual (such file does not exist) URL `http://localhost/page/.xyz` - which I would like to show to user, because it is not any sensitive file, just stupid id that starts with dot `.xyz`.

### CODE REVIEW

**Comment by mestrode** [comment]
Since files with trailing dot are usually hidden files in linux, I think is not a good idea to reveal them to the user.

**Comment by adaamz** [comment]
@mestrode I don't write anywhere that it is real file, it could be some identifier - which was my case.

**Comment by dg** [comment]
It's up to you. But I'll leave the safer one as the default.

**Comment by adaamz** [comment]
What is dangerous when the file doesn't exist?

**Comment by dg** [comment]
I can't think of anything. Then I'll merge it.

**Pull request merged**
